language: php
php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm
before_script: "composer install"
script: "vendor/bin/phpunit test"
sudo: false
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/b78839c0066e95e47dab
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false

