language: php

sudo: false

php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - if [[ "$TRAVIS_PHP_VERSION" != "hhvm" ]]; then phpenv config-rm xdebug.ini; fi
  - composer self-update
  - composer config github-oauth.github.com $GITHUB_TOKEN

install:
  - composer install --prefer-dist

script:
  - vendor/bin/phpunit test

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/b78839c0066e95e47dab
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
